version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false
    ports: 
      - 57771:1972
      - 57777:52773
      - 53773
      - 4040:8080
      - 4041:8081
      - 5000:5000
    volumes:
      - ./:/irisdev/app
